(()=>{'use strict';
const $=id=>document.getElementById(id),cv=$('game'),ctx=cv.getContext('2d'),PI=Math.PI,T=34;
const MAP=['################','#S.............#','#.............X#','#..............#','#......B.......#','#..............#','#..............#','#......P.......#','################'].map(r=>r.split(''));
const ROWS=MAP.length,COLS=MAP[0].length,WW=COLS*T,WH=ROWS*T;
const ui={msg:$('msg'),st:$('status'),ec:$('echoLabel'),fps:$('fps')};
let W=1,H=1,DPR=1,SC=1,OX=0,OY=0,last=performance.now(),fps=0,msgT=5;
let view='map',mode='game',zone='floor',won=false,pulse=0,events=[];
let player={kind:'player',x:55,y:55,vx:0,vy:0,a:0,r:11,cool:0};
let box={kind:'box',x:7.5*T,y:4.5*T,vx:0,vy:0,r:13,cool:0,locked:false};
let A=null,B=null,ptr={x:player.x+92,y:player.y},keys={},joy={on:false,dx:0,dy:0,cx:0,cy:0,id:0};
for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){if(MAP[y][x]==='S'){player.x=(x+.5)*T;player.y=(y+.5)*T;MAP[y][x]='.'}if(MAP[y][x]==='B')MAP[y][x]='.'}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b,c,d)=>Math.hypot(a-c,b-d);
const tile=v=>Math.floor(v/T);
const norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
function rec(k,area,data={}){events.push({t:Math.round(performance.now()),k,area,data,view,mode,zone,p:{x:Math.round(player.x),y:Math.round(player.y)},A:pack(A),B:pack(B)});if(events.length>100)events.shift()}
function pack(q){return q?{x:Math.round(q.x),y:Math.round(q.y),s:q.surface,n:[+q.nx.toFixed(2),+q.ny.toFixed(2)]}:null}
function say(t,s=2){ui.msg.textContent=t;ui.msg.style.display='block';msgT=s;rec('message','ui',{t})}
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=cv.width=Math.floor(innerWidth*DPR);H=cv.height=Math.floor(innerHeight*DPR);SC=Math.min(W/WW,H/WH);OX=(W-WW*SC)/2;OY=(H-WH*SC)/2}addEventListener('resize',resize);resize();
function solid(x,y){return x<0||y<0||x>=COLS||y>=ROWS||MAP[y][x]==='#'}
function hit(x,y,r){for(let yy=tile(y-r);yy<=tile(y+r);yy++)for(let xx=tile(x-r);xx<=tile(x+r);xx++){if(!solid(xx,yy))continue;let rx=xx*T,ry=yy*T,nx=clamp(x,rx,rx+T),ny=clamp(y,ry,ry+T);if((x-nx)**2+(y-ny)**2<r*r)return true}return false}
function inside(o){o.x=clamp(o.x,o.r+1,WW-o.r-1);o.y=clamp(o.y,o.r+1,WH-o.r-1)}
function move(o,dx,dy){let n=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/6)),sx=dx/n,sy=dy/n;for(let i=0;i<n;i++){o.x+=sx;inside(o);if(hit(o.x,o.y,o.r)){o.x-=sx;o.vx*=.12}o.y+=sy;inside(o);if(hit(o.x,o.y,o.r)){o.y-=sy;o.vy*=.12}}}
function screenToWorld(cx,cy){let r=cv.getBoundingClientRect();return{x:((cx-r.left)*DPR-OX)/SC,y:((cy-r.top)*DPR-OY)/SC}}
function basis(surface,a){let nx=0,ny=-1;if(surface==='ceiling'){nx=0;ny=1}else if(surface==='wall'){nx=Math.cos(a);ny=Math.sin(a)}let tx=-ny,ty=nx;return{nx,ny,tx,ty}}
function makePortal(label,surface,x,y,a=player.a){let b=basis(surface,a);return{label,surface,x:clamp(x,T,WW-T),y:clamp(y,T,WH-T),a,r:25,...b}}
function placePortal(label,surface=zone){let x=player.x+Math.cos(player.a)*84,y=player.y+Math.sin(player.a)*84,q=makePortal(label,surface,x,y,player.a);if(label==='A')A=q;else B=q;say(label+' '+surface);rec('place_'+label,'portal',{surface})}
function outPoint(q,r){for(let k=32;k<74;k+=8){let x=clamp(q.x+q.nx*k,r+2,WW-r-2),y=clamp(q.y+q.ny*k,r+2,WH-r-2);if(!hit(x,y,r))return{x,y,a:Math.atan2(q.ny,q.nx)}}return{x:q.x,y:q.y,a:Math.atan2(q.ny,q.nx)}}
function mapVelocity(vx,vy,from,to){let sp=Math.max(150,Math.hypot(vx,vy)),vt=vx*from.tx+vy*from.ty;let vn=Math.sqrt(Math.max(0,sp*sp-vt*vt));return{vx:to.nx*vn+to.tx*vt,vy:to.ny*vn+to.ty*vt}}
function cross(o){if(o.cool>0||o.locked||!A||!B)return;let atA=dist(o.x,o.y,A.x,A.y)<A.r,atB=dist(o.x,o.y,B.x,B.y)<B.r;if(!atA&&!atB)return;let from=atA?A:B,to=atA?B:A,e=outPoint(to,o.r),v=mapVelocity(o.vx,o.vy,from,to);o.x=e.x;o.y=e.y;o.a=e.a;o.vx=v.vx;o.vy=v.vy;o.cool=.45;pulse=1;say((o.kind==='box'?'Caja':'Jugador')+' '+from.label+'→'+to.label,.8);rec('cross','PortalPair',{from:from.surface,to:to.surface,speed:Math.round(Math.hypot(v.vx,v.vy))})}
function loopFall(){A=makePortal('A','floor',player.x,clamp(player.y+108,T,WH-T),0);B=makePortal('B','ceiling',player.x,clamp(player.y-108,T,WH-T),0);player.x=B.x;player.y=B.y+36;player.vx=0;player.vy=220;player.cool=.25;say('Loop caída');rec('loop_fall','PortalPair')}
function loopUp(){A=makePortal('A','ceiling',player.x,clamp(player.y-108,T,WH-T),0);B=makePortal('B','floor',player.x,clamp(player.y+108,T,WH-T),0);player.x=B.x;player.y=B.y-36;player.vx=0;player.vy=-220;player.cool=.25;say('Loop ascenso');rec('loop_up','PortalPair')}
function update(dt){let mx=joy.dx,my=joy.dy;if(keys.W)my--;if(keys.S)my++;if(keys.A)mx--;if(keys.D)mx++;let len=Math.hypot(mx,my),ix=0,iy=0;if(view==='fp'){let f=-my,s=mx;ix=Math.cos(player.a)*f+Math.cos(player.a+PI/2)*s;iy=Math.sin(player.a)*f+Math.sin(player.a+PI/2)*s}else{ix=len?mx/len:0;iy=len?my/len:0;if(len>.08)player.a=Math.atan2(iy,ix);else if(dist(ptr.x,ptr.y,player.x,player.y)>5)player.a=Math.atan2(ptr.y-player.y,ptr.x-player.x)}let speed=118,tx=len>.08?ix*speed:0,ty=len>.08?iy*speed:0;player.vx+=(tx-player.vx)*Math.min(1,dt*7);player.vy+=(ty-player.vy)*Math.min(1,dt*7);player.vy+=230*dt;if(len<=.08)player.vx*=Math.pow(.12,dt);move(player,player.vx*dt,player.vy*dt);player.cool=Math.max(0,player.cool-dt);cross(player);let d=dist(player.x,player.y,box.x,box.y);if(d<player.r+box.r+5&&d>0){let nx=(box.x-player.x)/d,ny=(box.y-player.y)/d;box.vx+=nx*(player.r+box.r+5-d)*12*dt;box.vy+=ny*(player.r+box.r+5-d)*12*dt}if(keys.F&&d<120){let gx=player.x+Math.cos(player.a)*55,gy=player.y+Math.sin(player.a)*55;box.vx+=(gx-box.x)*2.4*dt;box.vy+=(gy-box.y)*2.4*dt}box.vy+=230*dt;box.cool=Math.max(0,box.cool-dt);move(box,box.vx*dt,box.vy*dt);cross(box);box.vx*=Math.pow(.16,dt);box.vy*=Math.pow(.16,dt);let goal={x:14.5*T,y:1.5*T};if(!won&&dist(box.x,box.y,goal.x,goal.y)<34){won=true;box.locked=true;box.x=goal.x;box.y=goal.y;box.vx=box.vy=0;say('PUZZLE RESUELTO',4);rec('success','goal')}pulse=Math.max(0,pulse-dt*1.6)}
function background(){let g=ctx.createLinearGradient(0,0,0,H);if(mode==='game'){g.addColorStop(0,'#020303');g.addColorStop(.38,'#10141a');g.addColorStop(.70,'#2b2e32');g.addColorStop(1,'#050606')}else{g.addColorStop(0,'#020617');g.addColorStop(1,'#0f172a')}ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(mode==='game'){let r=ctx.createRadialGradient(W/2,H*.48,0,W/2,H*.48,Math.max(W,H)*.72);r.addColorStop(0,'rgba(255,255,255,.04)');r.addColorStop(1,'rgba(0,0,0,.42)');ctx.fillStyle=r;ctx.fillRect(0,0,W,H)}}
function tileMat(x,y,wall){let g=ctx.createLinearGradient(x,y,x,y+T);if(wall){g.addColorStop(0,'#2b3035');g.addColorStop(1,'#171a1e')}else{g.addColorStop(0,'#7c8084');g.addColorStop(1,'#565a5e')}ctx.fillStyle=g;ctx.fillRect(x,y,T,T);ctx.fillStyle='rgba(255,255,255,.04)';ctx.fillRect(x+3,y+4,T-6,2)}
function portalRing(q,col){if(!q)return;ctx.save();ctx.translate(q.x,q.y);let glow=ctx.createRadialGradient(0,0,6,0,0,40+pulse*20);glow.addColorStop(0,col+'66');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,43+pulse*15,0,PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(0,0,12,22,0,0,PI*2);ctx.clip();let gi=ctx.createLinearGradient(-12,-22,12,22);gi.addColorStop(0,col+'33');gi.addColorStop(.5,'rgba(255,255,255,.16)');gi.addColorStop(1,'rgba(0,0,0,.22)');ctx.fillStyle=gi;ctx.fillRect(-18,-28,36,56);for(let k=0;k<5;k++){ctx.globalAlpha=.42-k*.065;ctx.strokeStyle='#fff';ctx.beginPath();ctx.ellipse(0,0,9-k*1.4,16-k*2.2,0,0,PI*2);ctx.stroke()}ctx.restore();ctx.save();ctx.translate(q.x,q.y);ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,15,25,0,0,PI*2);ctx.stroke();ctx.strokeStyle=mode==='dev'?'#fbbf24':'#ffffffcc';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(q.nx*31,q.ny*31);ctx.stroke();if(mode==='dev'){ctx.fillStyle='#fff';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText(q.label+' '+q.surface,0,37)}ctx.restore()}
function drawPlayer(x,y,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle='#f8fafc';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-10,9);ctx.lineTo(-10,-9);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();ctx.restore()}
function drawMap(){ctx.save();ctx.translate(OX,OY);ctx.scale(SC,SC);ctx.fillStyle=mode==='game'?'#111417':'#0b1020';ctx.fillRect(0,0,WW,WH);for(let y=0;y<ROWS;y++)for(let xx=0;xx<COLS;xx++){let wall=MAP[y][xx]==='#';if(mode==='game')tileMat(xx*T,y*T,wall);else{ctx.fillStyle=wall?'#20252a':'#334155';ctx.fillRect(xx*T,y*T,T,T)}ctx.strokeStyle=mode==='dev'?'rgba(125,211,252,.15)':'rgba(255,255,255,.035)';ctx.strokeRect(xx*T,y*T,T,T)}let goal={x:14.5*T,y:1.5*T};ctx.strokeStyle='#a7f3d0';ctx.lineWidth=4;ctx.strokeRect(goal.x-20,goal.y-20,40,40);ctx.save();ctx.translate(box.x,box.y);ctx.rotate(won?0:performance.now()/1500);ctx.fillStyle=won?'#ecfdf5':'#f4f4f5';ctx.fillRect(-13,-13,26,26);ctx.strokeStyle='#fff';ctx.strokeRect(-13,-13,26,26);ctx.restore();portalRing(A,'#9fdcff');portalRing(B,'#c7b7ff');if(A&&B){ctx.strokeStyle='rgba(219,234,254,.45)';ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke()}drawPlayer(player.x,player.y,player.a);ctx.strokeStyle='#fb7185';ctx.beginPath();ctx.arc(ptr.x,ptr.y,8,0,PI*2);ctx.stroke();if(mode==='dev'){ctx.strokeStyle='rgba(255,255,255,.18)';ctx.beginPath();ctx.moveTo(player.x,player.y);ctx.arc(player.x,player.y,160,player.a-PI/2,player.a+PI/2);ctx.stroke();devText(10,16)}if(won){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,WW,WH);ctx.fillStyle='#ecfdf5';ctx.font='bold 20px system-ui';ctx.textAlign='center';ctx.fillText('PUZZLE RESUELTO',WW/2,WH/2)}ctx.restore()}
function project(o){if(!o)return null;let dx=o.x-player.x,dy=o.y-player.y,d=Math.hypot(dx,dy),a=norm(Math.atan2(dy,dx)-player.a);if(Math.abs(a)>PI/2||d<6)return null;let z=Math.cos(a)*d;if(z<4)return null;return{x:W/2+Math.tan(a)*W*.42,y:H*.56+(1/z)*10*DPR,s:Math.max(.35,Math.min(5,260/z)),d}}
function fpObject(o,type,col){let q=project(o);if(!q)return;ctx.save();ctx.translate(q.x,q.y);ctx.scale(q.s,q.s);ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=2/q.s;if(type==='portal'){ctx.beginPath();ctx.ellipse(0,0,11,20,0,0,PI*2);ctx.stroke();for(let k=0;k<4;k++){ctx.globalAlpha=.5-k*.1;ctx.beginPath();ctx.ellipse(0,0,8-k*1.7,15-k*2.5,0,0,PI*2);ctx.stroke()}ctx.globalAlpha=1;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo((o.nx||0)*18,(o.ny||0)*18);ctx.stroke()}else if(type==='box'){ctx.fillRect(-9,-9,18,18);ctx.strokeStyle='#fff';ctx.strokeRect(-9,-9,18,18)}else ctx.strokeRect(-14,-14,28,28);ctx.restore()}
function drawFp(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,mode==='game'?'#020303':'#020617');g.addColorStop(.30,mode==='game'?'#12171d':'#0f172a');g.addColorStop(.52,mode==='game'?'#2a2d31':'#1e293b');g.addColorStop(1,mode==='game'?'#080909':'#111827');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.035)';for(let i=0;i<5;i++){let yy=H*.17+i*H*.08;ctx.fillRect(0,yy,W,1*DPR)}ctx.fillStyle='rgba(255,255,255,.055)';ctx.fillRect(0,H*.34,W,H*.17);ctx.strokeStyle=mode==='game'?'rgba(255,255,255,.08)':'rgba(125,211,252,.18)';for(let i=0;i<15;i++){let y=H*.57+i*i*H*.0088;ctx.beginPath();ctx.moveTo(W*.07,y);ctx.lineTo(W*.93,y);ctx.stroke()}let par=Math.sin(player.a)*18*DPR+Math.sin(performance.now()/1700)*4*DPR;ctx.strokeStyle='rgba(255,255,255,.04)';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(W*(.14+i*.18)+par,H*.36);ctx.lineTo(W*(.04+i*.18)-par*.25,H*.86);ctx.stroke()}fpObject(A,'portal','#9fdcff');fpObject(B,'portal','#c7b7ff');fpObject(box,'box','#f4f4f5');fpObject({x:14.5*T,y:1.5*T},'goal','#a7f3d0');ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(W/2-12*DPR,H/2);ctx.lineTo(W/2+12*DPR,H/2);ctx.moveTo(W/2,H/2-12*DPR);ctx.lineTo(W/2,H/2+12*DPR);ctx.stroke();ctx.fillStyle='#ffffffc0';ctx.font=`${11*DPR}px system-ui`;ctx.textAlign='center';ctx.fillText(mode==='game'?'PORTAL WINDOW':'DEV VIEW '+zone,W/2,24*DPR);ctx.fillText('techo / frente / piso · parallax · velocidad conservada',W/2,42*DPR);if(mode==='dev')devText(12*DPR,72*DPR)}
function devText(x,y){ctx.save();ctx.fillStyle='#e0f2fe';ctx.font=`${10*DPR}px ui-monospace,monospace`;['v1.7.1 aesthetic clarity','view '+view+' mode '+mode+' zone '+zone,'A '+JSON.stringify(pack(A)),'B '+JSON.stringify(pack(B)),'p v '+Math.round(player.vx)+','+Math.round(player.vy),'events '+events.length].forEach((t,i)=>ctx.fillText(t,x,y+i*13*DPR));ctx.restore()}
function overlay(){ctx.fillStyle='rgba(255,255,255,.68)';ctx.font=`${10*DPR}px system-ui`;ctx.textAlign='left';ctx.fillText('v1.7.1 · '+mode+' · '+(view==='fp'?'1P':'map')+' · '+zone,12*DPR,H-14*DPR)}
function exportPacket(){let packet={CHRONORIFT_PACKET:{build:'pages-v1.7.1_aesthetic_clarity',PortalPair:{A:pack(A),B:pack(B)},events,visual:{mode,clarity:['ceiling','front','floor','distance','parallax']}}};let txt=JSON.stringify(packet,null,2);navigator.clipboard?.writeText(txt).then(()=>say('Export copiado')).catch(()=>console.log(txt))}
function makeControls(){let bar=document.createElement('div');bar.style.cssText='position:fixed;left:8px;right:8px;top:calc(env(safe-area-inset-top) + 88px);display:none;gap:6px;flex-wrap:wrap;z-index:9';function b(t,f){let el=document.createElement('button');el.textContent=t;el.style.minHeight='32px';el.onclick=f;bar.appendChild(el)}b('A Piso',()=>{zone='floor';placePortal('A','floor')});b('B Techo',()=>{zone='ceiling';placePortal('B','ceiling')});b('B Piso',()=>{zone='floor';placePortal('B','floor')});b('Loop Caída',loopFall);b('Loop Ascenso',loopUp);b('Export',exportPacket);document.body.appendChild(bar);$('helpBtn').onclick=()=>{bar.style.display=bar.style.display==='none'?'flex':'none'};$('debugBtn').textContent='DEV';$('debugBtn').onclick=()=>{mode=mode==='game'?'dev':'game';$('debugBtn').textContent=mode==='game'?'DEV':'GAME';say(mode==='game'?'Game premium':'Dev full info')}}
document.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();let a=b.dataset.act;if(a==='A')placePortal('A',zone);if(a==='B')placePortal('B',zone);if(a==='L'){view=view==='map'?'fp':'map';say(view==='fp'?'Vista 1P':'Mapa')}if(a==='T')loopFall();if(a==='F'){keys.F=1;setTimeout(()=>keys.F=0,700);say('Field')}if(a==='X'){A=B=null;say('Clear')}}));
cv.addEventListener('pointerdown',e=>{if(view==='fp'){let r=cv.getBoundingClientRect(),ny=(e.clientY-r.top)/r.height,nx=((e.clientX-r.left)/r.width-.5)*2;zone=ny<.34?'ceiling':ny>.66?'floor':'wall';player.a=norm(player.a+nx*.06);ptr.x=clamp(player.x+Math.cos(player.a)*95,T,WW-T);ptr.y=clamp(player.y+Math.sin(player.a)*95,T,WH-T)}else ptr=screenToWorld(e.clientX,e.clientY)});cv.addEventListener('pointermove',e=>{if(view!=='fp')ptr=screenToWorld(e.clientX,e.clientY)});
let je=$('joy'),kn=$('knob');function jm(e){if(!joy.on||e.pointerId!==joy.id)return;let dx=e.clientX-joy.cx,dy=e.clientY-joy.cy,d=Math.hypot(dx,dy),m=38;if(d>m){dx=dx/d*m;dy=dy/d*m}joy.dx=Math.abs(dx/m)<.08?0:dx/m;joy.dy=Math.abs(dy/m)<.08?0:dy/m;kn.style.left=38+dx+'px';kn.style.top=38+dy+'px'}je.addEventListener('pointerdown',e=>{let r=je.getBoundingClientRect();joy={on:true,id:e.pointerId,dx:0,dy:0,cx:r.left+r.width/2,cy:r.top+r.height/2};je.setPointerCapture&&je.setPointerCapture(e.pointerId);jm(e)});je.addEventListener('pointermove',jm);function jee(e){if(e.pointerId!==joy.id)return;joy.on=false;joy.dx=joy.dy=0;kn.style.left='38px';kn.style.top='38px'}je.addEventListener('pointerup',jee);je.addEventListener('pointercancel',jee);
document.addEventListener('keydown',e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=1;if(e.code==='KeyL')view=view==='map'?'fp':'map';if(e.code==='KeyM')mode=mode==='game'?'dev':'game';if(e.code==='Digit1')loopFall();if(e.code==='Digit2')loopUp()});document.addEventListener('keyup',e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=0});
function frame(n){let dt=Math.min(.05,(n-last)/1000);fps=fps?fps*.9+(1/dt)*.1:1/dt;last=n;update(dt);background();view==='fp'?drawFp():drawMap();overlay();if(msgT>0){msgT-=dt;if(msgT<=0)ui.msg.style.display='none'}ui.st.textContent=won?'resuelto':'pages-v1.7.1';ui.ec.textContent=mode+' '+(view==='fp'?'1P':'map');ui.fps.textContent='fps '+Math.round(fps);requestAnimationFrame(frame)}
makeControls();say('v1.7.1 claridad estética GAME');requestAnimationFrame(frame);
})();