(()=>{'use strict';
const $=id=>document.getElementById(id),cv=$('game'),ctx=cv.getContext('2d'),PI=Math.PI,T=34;
const MAP=['################','#S.............#','#.............X#','#..............#','#......B.......#','#..............#','#..............#','#......P.......#','################'].map(r=>r.split(''));
const R=MAP.length,C=MAP[0].length,WW=C*T,WH=R*T,ui={msg:$('msg'),st:$('status'),ec:$('echoLabel'),fp:$('fps')};
let W=1,H=1,D=1,sc=1,ox=0,oy=0,last=performance.now(),fps=0,view='map',zone='wall',won=0,msgT=4,logs=[];
let p={kind:'player',x:60,y:60,vx:0,vy:0,a:0,r:11,cool:0,gx:0,gy:0,gt:0},box={kind:'box',x:7.5*T,y:4.5*T,vx:0,vy:0,r:13,cool:0,gx:0,gy:0,gt:0,lock:0};
let A=null,B=null,ptr={x:p.x+90,y:p.y},keys={},joy={on:0,dx:0,dy:0,cx:0,cy:0,id:0},events=[];
for(let y=0;y<R;y++)for(let x=0;x<C;x++){if(MAP[y][x]=='S'){p.x=(x+.5)*T;p.y=(y+.5)*T;MAP[y][x]='.'}if(MAP[y][x]=='B')MAP[y][x]='.'}
function rec(k,a,d={}){events.push({t:Math.round(performance.now()),k,a,d,view,zone,p:{x:Math.round(p.x),y:Math.round(p.y)},A,B});if(events.length>80)events.shift()}
function say(t,s=2){ui.msg.textContent=t;ui.msg.style.display='block';msgT=s;rec('msg','ui',{t})}
function resize(){D=Math.min(2,devicePixelRatio||1);W=cv.width=innerWidth*D;H=cv.height=innerHeight*D;sc=Math.min(W/WW,H/WH);ox=(W-WW*sc)/2;oy=(H-WH*sc)/2}addEventListener('resize',resize);resize();
const cl=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b,c,d)=>Math.hypot(a-c,b-d),tile=v=>Math.floor(v/T),norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
function solid(x,y){return x<0||y<0||x>=C||y>=R||MAP[y][x]=='#'}
function hit(x,y,r){for(let yy=tile(y-r);yy<=tile(y+r);yy++)for(let xx=tile(x-r);xx<=tile(x+r);xx++){if(!solid(xx,yy))continue;let rx=xx*T,ry=yy*T,nx=cl(x,rx,rx+T),ny=cl(y,ry,ry+T);if((x-nx)**2+(y-ny)**2<r*r)return 1}return 0}
function inside(o){o.x=cl(o.x,o.r+1,WW-o.r-1);o.y=cl(o.y,o.r+1,WH-o.r-1)}
function move(o,dx,dy){let n=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/6)),sx=dx/n,sy=dy/n;for(let i=0;i<n;i++){o.x+=sx;inside(o);if(hit(o.x,o.y,o.r)){o.x-=sx;o.vx*=.1}o.y+=sy;inside(o);if(hit(o.x,o.y,o.r)){o.y-=sy;o.vy*=.1}}}
function scr(cx,cy){let r=cv.getBoundingClientRect();return{x:((cx-r.left)*D-ox)/sc,y:((cy-r.top)*D-oy)/sc}}
function normal(s,a){if(s=='floor')return{nx:0,ny:-1};if(s=='ceiling')return{nx:0,ny:1};return{nx:Math.cos(a),ny:Math.sin(a)}}
function portal(surface,kind){let x=ptr.x,y=ptr.y,a=p.a;if(kind=='auto'){x=cl(p.x+Math.cos(p.a)*75,T,WW-T);y=cl(p.y+Math.sin(p.a)*75,T,WH-T)}let n=normal(surface,a);return{x,y,a,surface,nx:n.nx,ny:n.ny}}
function setA(s='floor'){A=portal(s,'auto');say('A '+s);rec('setA','portal',{s})}
function setB(s=zone){B=portal(s,'auto');say('B '+s);rec('setB','portal',{s})}
function loopFall(){A={x:p.x,y:cl(p.y+92,T,WH-T),a:0,surface:'floor',nx:0,ny:-1};B={x:p.x,y:cl(p.y-92,T,WH-T),a:0,surface:'ceiling',nx:0,ny:1};p.x=B.x;p.y=B.y+26;p.vx=0;p.vy=210;p.gx=0;p.gy=1;p.gt=6;p.cool=.4;say('Loop caída iniciado');rec('loop_fall','native')}
function loopUp(){A={x:p.x,y:cl(p.y-92,T,WH-T),a:0,surface:'ceiling',nx:0,ny:1};B={x:p.x,y:cl(p.y+92,T,WH-T),a:0,surface:'floor',nx:0,ny:-1};p.x=B.x;p.y=B.y-26;p.vx=0;p.vy=-210;p.gx=0;p.gy=-1;p.gt=6;p.cool=.4;say('Loop ascenso iniciado');rec('loop_up','native')}
function exit(to,r){let a=Math.atan2(to.ny,to.nx);for(let k=26;k<60;k+=8){let x=cl(to.x+to.nx*k,r+2,WW-r-2),y=cl(to.y+to.ny*k,r+2,WH-r-2);if(!hit(x,y,r))return{x,y,a}}return{x:to.x,y:to.y,a}}
function cross(o){if(o.cool>0||!A||!B||o.lock)return;let ca=dist(o.x,o.y,A.x,A.y)<24,cb=dist(o.x,o.y,B.x,B.y)<24;if(!ca&&!cb)return;let to=ca?B:A,e=exit(to,o.r),sp=Math.max(160,Math.hypot(o.vx,o.vy)*.92);o.x=e.x;o.y=e.y;o.a=e.a;o.vx=to.nx*sp;o.vy=to.ny*sp;o.gx=to.nx;o.gy=to.ny;o.gt=5;o.cool=.45;say((o.kind=='box'?'Caja':'Jugador')+' portal '+to.surface,.8);rec('cross','portal',{to:to.surface})}
function grav(o,dt){if(o.gt>0&&!o.lock){o.vx+=o.gx*240*dt;o.vy+=o.gy*240*dt;o.gt=Math.max(0,o.gt-dt)}}
function update(dt){let mx=joy.dx,my=joy.dy;if(keys.W)my--;if(keys.S)my++;if(keys.A)mx--;if(keys.D)mx++;let l=Math.hypot(mx,my),ix=0,iy=0;if(view=='fp'){let f=-my,s=mx;ix=Math.cos(p.a)*f+Math.cos(p.a+PI/2)*s;iy=Math.sin(p.a)*f+Math.sin(p.a+PI/2)*s}else{ix=l?mx/l:0;iy=l?my/l:0;if(l>.08)p.a=Math.atan2(iy,ix);else if(dist(ptr.x,ptr.y,p.x,p.y)>5)p.a=Math.atan2(ptr.y-p.y,ptr.x-p.x)}let sp=118,tx=l>.08?ix*sp:0,ty=l>.08?iy*sp:0;p.vx+=(tx-p.vx)*Math.min(1,dt*7);p.vy+=(ty-p.vy)*Math.min(1,dt*7);grav(p,dt);if(l<=.08&&p.gt<=0){p.vx*=Math.pow(.12,dt);p.vy*=Math.pow(.12,dt)}move(p,p.vx*dt,p.vy*dt);p.cool=Math.max(0,p.cool-dt);cross(p);let d=dist(p.x,p.y,box.x,box.y);if(d<p.r+box.r+5&&d>0){let nx=(box.x-p.x)/d,ny=(box.y-p.y)/d;box.vx+=nx*(p.r+box.r+5-d)*12*dt;box.vy+=ny*(p.r+box.r+5-d)*12*dt}if(keys.F&&d<115){let gx=p.x+Math.cos(p.a)*55,gy=p.y+Math.sin(p.a)*55;box.vx+=(gx-box.x)*2.4*dt;box.vy+=(gy-box.y)*2.4*dt}grav(box,dt);box.cool=Math.max(0,box.cool-dt);move(box,box.vx*dt,box.vy*dt);cross(box);box.vx*=Math.pow(box.gt>0?.98:.14,dt);box.vy*=Math.pow(box.gt>0?.98:.14,dt);let goal={x:14.5*T,y:2.5*T};if(!won&&dist(box.x,box.y,goal.x,goal.y)<30){won=1;box.lock=1;box.x=goal.x;box.y=goal.y;box.vx=box.vy=0;say('PUZZLE RESUELTO',4);rec('success','goal')}}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#050607');g.addColorStop(.55,'#11151a');g.addColorStop(1,'#030405');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawPtl(r,l,c){if(!r)return;ctx.save();ctx.translate(r.x,r.y);ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,12,22,0,0,PI*2);ctx.stroke();ctx.globalAlpha=.5;for(let k=0;k<3;k++){ctx.beginPath();ctx.ellipse(0,0,8-k*2,15-k*3,0,0,PI*2);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(r.nx*28,r.ny*28);ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText(l,0,4);ctx.font='8px system-ui';ctx.fillText(r.surface,0,32);ctx.restore()}
function tri(x,y,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle='#f8fafc';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-10,9);ctx.lineTo(-10,-9);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();ctx.restore()}
function drawMap(){ctx.save();ctx.translate(ox,oy);ctx.scale(sc,sc);ctx.fillStyle='#101214';ctx.fillRect(0,0,WW,WH);for(let y=0;y<R;y++)for(let x=0;x<C;x++){ctx.fillStyle=MAP[y][x]=='#'?'#20252a':'#73777b';ctx.fillRect(x*T,y*T,T,T);ctx.strokeStyle='rgba(255,255,255,.03)';ctx.strokeRect(x*T,y*T,T,T)}ctx.strokeStyle='rgba(255,255,255,.14)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.arc(p.x,p.y,160,p.a-PI/2,p.a+PI/2);ctx.closePath();ctx.stroke();let goal={x:14.5*T,y:2.5*T};ctx.strokeStyle='#a7f3d0';ctx.lineWidth=4;ctx.strokeRect(goal.x-20,goal.y-20,40,40);ctx.save();ctx.translate(box.x,box.y);ctx.rotate(won?0:performance.now()/1500);ctx.fillStyle=won?'#ecfdf5':'#f4f4f5';ctx.fillRect(-13,-13,26,26);ctx.strokeStyle=box.gt>0?'#fbbf24':'#fff';ctx.strokeRect(-13,-13,26,26);ctx.restore();drawPtl(A,'A','#b9e1ff');drawPtl(B,'B','#ebdcff');if(A&&B){ctx.strokeStyle='rgba(219,234,254,.45)';ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke()}tri(p.x,p.y,p.a);ctx.strokeStyle='#fb7185';ctx.beginPath();ctx.arc(ptr.x,ptr.y,8,0,PI*2);ctx.stroke();if(won){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,WW,WH);ctx.fillStyle='#ecfdf5';ctx.font='bold 20px system-ui';ctx.textAlign='center';ctx.fillText('PUZZLE RESUELTO',WW/2,WH/2)}ctx.restore()}
function proj(o){if(!o)return null;let dx=o.x-p.x,dy=o.y-p.y,d=Math.hypot(dx,dy),a=norm(Math.atan2(dy,dx)-p.a);if(Math.abs(a)>PI/2||d<6)return null;let z=Math.cos(a)*d;if(z<4)return null;return{x:W/2+Math.tan(a)*W*.42,y:H*.56,s:Math.max(.35,Math.min(5,260/z))}}
function fpThing(o,type,c){if(!o)return;let q=proj(o);if(!q)return;ctx.save();ctx.translate(q.x,q.y);ctx.scale(q.s,q.s);ctx.strokeStyle=c;ctx.fillStyle=c;ctx.lineWidth=2/q.s;if(type=='portal'){ctx.beginPath();ctx.ellipse(0,0,10,18,0,0,PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo((o.nx||0)*18,(o.ny||0)*18);ctx.stroke()}else if(type=='box'){ctx.fillRect(-9,-9,18,18);ctx.strokeStyle='#fff';ctx.strokeRect(-9,-9,18,18)}else ctx.strokeRect(-14,-14,28,28);ctx.restore()}
function drawFp(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#06070a');g.addColorStop(.55,'#15191f');g.addColorStop(1,'#2b2d30');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<10;i++){let y=H*.58+i*i*H*.012;ctx.beginPath();ctx.moveTo(W*.08,y);ctx.lineTo(W*.92,y);ctx.stroke()}fpThing(A,'portal','#b9e1ff');fpThing(B,'portal','#ebdcff');fpThing(box,'box','#f4f4f5');fpThing({x:14.5*T,y:2.5*T},'goal','#a7f3d0');ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(W/2-12*D,H/2);ctx.lineTo(W/2+12*D,H/2);ctx.moveTo(W/2,H/2-12*D);ctx.lineTo(W/2,H/2+12*D);ctx.stroke();ctx.fillStyle='#ffffffc0';ctx.font=`${11*D}px system-ui`;ctx.textAlign='center';ctx.fillText('1P '+zone+' · Loop nativo',W/2,24*D);ctx.fillText('Piso sale arriba · Techo sale abajo',W/2,42*D)}
function overlay(){ctx.fillStyle='rgba(255,255,255,.65)';ctx.font=`${10*D}px system-ui`;ctx.textAlign='left';ctx.fillText('v1.6.6 · '+(view=='fp'?'1P':'map')+' · zone '+zone,12*D,H-14*D)}
function exportPacket(){let packet={CHRONORIFT_LIVE_TUNING_PACKET:{build:'pages-v1.6.6_view_hotfix',events,runtime:'native_vertical_loop',view_hotfix:true,vertical_controls_native:true}};let txt=JSON.stringify(packet,null,2);navigator.clipboard?.writeText(txt).then(()=>say('Export copiado')).catch(()=>{console.log(txt);say('Export en consola')})}
function makeTune(){let bar=document.createElement('div');bar.style.cssText='position:fixed;left:8px;right:8px;top:calc(env(safe-area-inset-top) + 88px);display:none;gap:6px;flex-wrap:wrap;z-index:9';function b(t,f){let x=document.createElement('button');x.textContent=t;x.style.minHeight='32px';x.onclick=f;bar.appendChild(x)}b('A Piso',()=>setA('floor'));b('B Techo',()=>setB('ceiling'));b('B Piso',()=>setB('floor'));b('Loop Caída',loopFall);b('Loop Ascenso',loopUp);b('Good',()=>rec('good','feel'));b('Blocker',()=>rec('blocker','play'));b('Export',exportPacket);document.body.appendChild(bar);$('debugBtn').textContent='Loop';$('debugBtn').onclick=()=>{bar.style.display=bar.style.display=='none'?'flex':'none'}}
let field=false;document.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();let a=b.dataset.act;if(a=='A')setA(zone=='ceiling'?'ceiling':'floor');if(a=='B')setB(zone);if(a=='L'){view=view=='map'?'fp':'map';say(view=='fp'?'Vista 1P':'Mapa')}if(a=='F'){keys.F=1;setTimeout(()=>keys.F=0,700);say('Field')}if(a=='X'){A=B=null;say('Clear')}}));
cv.addEventListener('pointerdown',e=>{if(view=='fp'){let r=cv.getBoundingClientRect(),ny=(e.clientY-r.top)/r.height,nx=((e.clientX-r.left)/r.width-.5)*2;zone=ny<.34?'ceiling':ny>.66?'floor':'wall';p.a=norm(p.a+nx*.06);ptr.x=cl(p.x+Math.cos(p.a)*95,T,WW-T);ptr.y=cl(p.y+Math.sin(p.a)*95,T,WH-T)}else ptr=scr(e.clientX,e.clientY)});cv.addEventListener('pointermove',e=>{if(view!='fp')ptr=scr(e.clientX,e.clientY)});
let je=$('joy'),kn=$('knob');function jm(e){if(!joy.on||e.pointerId!==joy.id)return;let dx=e.clientX-joy.cx,dy=e.clientY-joy.cy,d=Math.hypot(dx,dy),m=38;if(d>m){dx=dx/d*m;dy=dy/d*m}joy.dx=Math.abs(dx/m)<.08?0:dx/m;joy.dy=Math.abs(dy/m)<.08?0:dy/m;kn.style.left=38+dx+'px';kn.style.top=38+dy+'px'}je.addEventListener('pointerdown',e=>{let r=je.getBoundingClientRect();joy={on:1,id:e.pointerId,dx:0,dy:0,cx:r.left+r.width/2,cy:r.top+r.height/2};je.setPointerCapture&&je.setPointerCapture(e.pointerId);jm(e)});je.addEventListener('pointermove',jm);function jee(e){if(e.pointerId!==joy.id)return;joy.on=0;joy.dx=joy.dy=0;kn.style.left='38px';kn.style.top='38px'}je.addEventListener('pointerup',jee);je.addEventListener('pointercancel',jee);
document.addEventListener('keydown',e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=1;if(e.code=='KeyL')view=view=='map'?'fp':'map';if(e.code=='Digit1')loopFall();if(e.code=='Digit2')loopUp()});document.addEventListener('keyup',e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=0});
function frame(n){let dt=Math.min(.05,(n-last)/1000);fps=fps?fps*.9+(1/dt)*.1:1/dt;last=n;update(dt);bg();view=='fp'?drawFp():drawMap();overlay();if(msgT>0){msgT-=dt;if(msgT<=0)ui.msg.style.display='none'}ui.st.textContent=won?'resuelto':'pages-v1.6.6';ui.ec.textContent=view=='fp'?'1P '+zone:'vertical loop';ui.fp.textContent='fps '+Math.round(fps);requestAnimationFrame(frame)}
makeTune();say('v1.6.6: View hotfix + loop nativo');requestAnimationFrame(frame);
})();