(()=>{'use strict';
const $=id=>document.getElementById(id),cv=$('game'),c=cv.getContext('2d'),TAU=Math.PI*2,PI=Math.PI;
let W=1,H=1,D=1,last=performance.now(),fps=0,view='map',msgT=3,showGizmo=0,activeSurface='floor',mode='free';
const ui={m:$('msg'),st:$('status'),ec:$('echoLabel'),fps:$('fps')};
const world={w:980,h:560,g:9.8,areas:[['RECEIVING',70,90,260,150],['PORTAL TEST',380,95,260,150],['GOAL BAY',730,90,180,150],['LOOP H',70,330,840,120]]};
let p={x:130,y:170,z:0,vx:0,vy:0,vz:0,a:0,r:15,c:0},box={x:320,y:185,z:0,vx:0,vy:0,vz:0,r:18,grab:0,done:0,c:0,surface:'floor'};
let goal={x:850,y:170,r:45},A=null,B=null,ptr={x:360,y:180},keys={},joy={on:0,dx:0,dy:0,cx:0,cy:0,id:0},look={on:0,id:0,x:0},fx=[],trail=[],sample=0,cut={on:0,t:0,prev:'map',reason:''},tunnel=0,audioOn=0;
const surfaces=['floor','wall','ceiling'],cl=(v,a,b)=>Math.max(a,Math.min(b,v)),hyp=(a,b,c,d)=>Math.hypot(a-c,b-d),norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
function resize(){D=Math.min(2,devicePixelRatio||1);W=cv.width=innerWidth*D;H=cv.height=innerHeight*D}onresize=resize;resize();
function say(t,s=2){ui.m.textContent=t;ui.m.style.display='block';msgT=s}
function basis(nx,ny){let l=Math.hypot(nx,ny)||1;nx/=l;ny/=l;return{nx,ny,tx:-ny,ty:nx}}
function makePortal(label,x,y,surface=activeSurface,nx=1,ny=0){if(surface=='wall'){nx=x<world.w/2?1:-1;ny=0}else if(surface=='ceiling'){nx=0;ny=1}else if(surface=='floor'){nx=0;ny=-1}return{label,x:cl(x,50,world.w-50),y:cl(y,55,world.h-55),surface,r:34,...basis(nx,ny)}}
function setAreaPreset(kind){if(kind=='loopH'){mode='loopH';view='loopH';A=makePortal('A',140,390,'wall',1,0);B=makePortal('B',840,390,'wall',-1,0);p.x=190;p.y=390;box.x=300;box.y=390;say('Loop horizontal: entra y sale entre portales laterales');}
 if(kind=='loopV'){mode='loopV';view='loopV';A=makePortal('A',500,95,'ceiling',0,1);B=makePortal('B',500,495,'floor',0,-1);p.x=500;p.y=185;p.z=120;p.vz=0;box.x=560;box.y=360;box.z=0;say('Loop vertical: gravedad 9.8 m/s² + tubo techo→piso');}
 if(kind=='delivery'){mode='delivery';view='gizmo';A=makePortal('A',420,170,'floor',1,0);B=makePortal('B',760,170,'floor',1,0);startCut('entrega de caja');say('Delivery Path: portal físico hacia meta');}}
function startCut(reason='alerta'){if(!cut.on){cut={on:1,t:2.7,prev:view,reason};say('ALERTA: cuarto completo · '+reason,2.4)}}
function move(o,dx,dy){o.x=cl(o.x+dx,o.r,world.w-o.r);o.y=cl(o.y+dy,o.r,world.h-o.r)}
function mapVel(vx,vy,from,to){let sp=Math.max(110,Math.hypot(vx,vy)),vt=vx*from.tx+vy*from.ty,vn=Math.sqrt(Math.max(0,sp*sp-vt*vt));return{vx:to.nx*vn+to.tx*vt,vy:to.ny*vn+to.ty*vt,sp}}
function portalExit(q,o){let d=o.r+38;return{x:cl(q.x+q.nx*d,o.r,world.w-o.r),y:cl(q.y+q.ny*d,o.r,world.h-o.r)}}
function addFx(f,t,o,v){fx.push({x1:f.x,y1:f.y,x2:t.x+t.nx*110,y2:t.y+t.ny*110,life:1.8,k:o===box?'crate':'player',sp:v.sp});if(fx.length>20)fx.shift()}
function cross(o){if(o.c>0||!A||!B||o.done)return;let nearA=hyp(o.x,o.y,A.x,A.y)<A.r,nearB=hyp(o.x,o.y,B.x,B.y)<B.r;if(!nearA&&!nearB)return;let f=nearA?A:B,t=nearA?B:A,e=portalExit(t,o),v=mapVel(o.vx,o.vy,f,t);addFx(f,t,o,v);o.x=e.x;o.y=e.y;o.vx=v.vx;o.vy=v.vy;o.a=Math.atan2(t.ny,t.nx);o.c=.55;tunnel=o===p?1.1:tunnel;if((f.surface=='ceiling'&&t.surface=='floor')||(f.surface=='floor'&&t.surface=='ceiling')){o.vz=-Math.max(180,Math.abs(o.vz)+v.sp*.75);fx.push({x1:t.x,y1:t.y,x2:t.x,y2:t.y-150,life:1.6,k:'gravity',sp:Math.abs(o.vz)})}say((o===box?'Caja':'Jugador')+' '+f.label+'→'+t.label+' vel '+Math.round(v.sp),1.1)}
function toggleGrab(){if(box.done)return say('Caja fijada en meta');let d=hyp(p.x,p.y,box.x,box.y);if(box.grab){box.grab=0;say('Caja soltada')}else if(d<78){box.grab=1;say('Grab ON: caja anclada a herramienta')}else say('Acércate a la caja')}
function finish(){if(box.done)return;box.done=1;box.grab=0;box.x=goal.x;box.y=goal.y;box.vx=box.vy=0;startCut('entrega completada');say('PUZZLE RESUELTO → STAGE 2 DESBLOQUEADO',5)}
function update(dt){if(cut.on){cut.t-=dt;if(cut.t<=0){view=cut.prev;cut.on=0;say('Regreso a '+view,.9)}}let mx=joy.dx,my=joy.dy;if(keys.W)my--;if(keys.S)my++;if(keys.A)mx--;if(keys.D)mx++;let l=Math.hypot(mx,my),ix=l?mx/l:0,iy=l?my/l:0;if(view=='fp'&&!cut.on){if(keys.Q)p.a-=dt*2;if(keys.E)p.a+=dt*2;let f=-my,s=mx;ix=Math.cos(p.a)*f+Math.cos(p.a+PI/2)*s;iy=Math.sin(p.a)*f+Math.sin(p.a+PI/2)*s}else if(l>.08){p.a=Math.atan2(iy,ix)}let sp=132;p.vx+=((l>.08?ix*sp:0)-p.vx)*Math.min(1,dt*7);p.vy+=((l>.08?iy*sp:0)-p.vy)*Math.min(1,dt*7);if(l<=.08){p.vx*=Math.pow(.18,dt);p.vy*=Math.pow(.18,dt)}move(p,p.vx*dt,p.vy*dt);p.c=Math.max(0,p.c-dt);cross(p);
 if(mode=='loopV'){p.vz+=world.g*42*dt;p.z+=p.vz*dt;if(p.z<0){p.z=0;p.vz=0}if(p.z>210){p.z=210;p.vz*=-.2}}
 let d=hyp(p.x,p.y,box.x,box.y);if(box.grab&&!box.done){let tx=p.x+Math.cos(p.a)*42,ty=p.y+Math.sin(p.a)*42;box.vx+=(tx-box.x)*15*dt;box.vy+=(ty-box.y)*15*dt;box.vx*=Math.pow(.12,dt);box.vy*=Math.pow(.12,dt)}else if(d<p.r+box.r+9&&d>0&&!box.done){box.vx+=(box.x-p.x)/d*130*dt;box.vy+=(box.y-p.y)/d*130*dt}move(box,box.vx*dt,box.vy*dt);cross(box);if(!box.done){box.vx*=Math.pow(box.grab?.18:.04,dt);box.vy*=Math.pow(box.grab?.18:.04,dt)}if(hyp(box.x,box.y,goal.x,goal.y)<goal.r){finish()}sample+=dt;if(sample>.05){sample=0;trail.push({x:p.x,y:p.y,z:p.z,bx:box.x,by:box.y,t:performance.now()});if(trail.length>240)trail.shift()}for(let f of fx)f.life-=dt;fx=fx.filter(f=>f.life>0);tunnel=Math.max(0,tunnel-dt)}
function roomTransform(){let sc=Math.min(W/world.w,H/world.h)*.92,ox=(W-world.w*sc)/2,oy=(H-world.h*sc)/2;return{sc,ox,oy}}
function areaBoxes(){for(const [name,x,y,w,h] of world.areas){c.fillStyle='rgba(255,255,255,.035)';c.fillRect(x,y,w,h);c.strokeStyle='rgba(255,255,255,.09)';c.strokeRect(x,y,w,h);c.fillStyle='rgba(219,234,254,.55)';c.font='bold 13px system-ui';c.fillText(name,x+12,y+20)}}
function surfaceGrid(){c.fillStyle='#171b20';c.fillRect(0,0,world.w,world.h);for(let x=0;x<world.w;x+=34){c.strokeStyle='rgba(255,255,255,.035)';c.beginPath();c.moveTo(x,45);c.lineTo(x,world.h-30);c.stroke()}for(let y=45;y<world.h;y+=34){c.beginPath();c.moveTo(0,y);c.lineTo(world.w,y);c.stroke()}c.fillStyle='rgba(80,88,94,.8)';c.fillRect(0,45,world.w,34);c.fillStyle='rgba(128,137,145,.95)';c.fillRect(0,world.h-72,world.w,42);c.fillStyle='rgba(88,96,104,.8)';c.fillRect(0,45,38,world.h-85);c.fillRect(world.w-38,45,38,world.h-85);c.fillStyle='#dbeafe';c.font='bold 12px system-ui';c.fillText('CEILING',12,69);c.fillText('FLOOR',12,world.h-45);c.save();c.translate(18,world.h/2);c.rotate(-PI/2);c.fillText('WALL',0,0);c.restore();c.save();c.translate(world.w-18,world.h/2);c.rotate(PI/2);c.fillText('WALL',0,0);c.restore()}
function drawArrow(x1,y1,x2,y2,col='#93c5fd',a=1){c.save();c.globalAlpha=a;c.strokeStyle=col;c.fillStyle=col;c.lineWidth=4;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();let an=Math.atan2(y2-y1,x2-x1);c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-Math.cos(an-.55)*16,y2-Math.sin(an-.55)*16);c.lineTo(x2-Math.cos(an+.55)*16,y2-Math.sin(an+.55)*16);c.closePath();c.fill();c.restore()}
function label(txt,x,y,col='#e0f2fe'){c.fillStyle='rgba(0,0,0,.58)';c.fillRect(x-44,y-25,88,18);c.fillStyle=col;c.font='bold 11px system-ui';c.textAlign='center';c.fillText(txt,x,y-12)}
function portal(q,col){if(!q)return;c.save();c.translate(q.x,q.y);let ang=q.surface=='floor'?0:q.surface=='ceiling'?0:PI/2;c.strokeStyle=col;c.lineWidth=6;c.beginPath();c.ellipse(0,0,q.surface=='wall'?12:28,q.surface=='wall'?34:14,ang,0,TAU);c.stroke();c.fillStyle='rgba(147,197,253,.10)';c.fill();c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(-28,-18,56,36);c.restore();label(q.label+' '+q.surface.toUpperCase(),q.x,q.y-25,col);drawArrow(q.x,q.y,q.x+q.nx*58,q.y+q.ny*58,col,.75)}
function crate(){c.save();c.translate(box.x,box.y-box.z*.25);c.fillStyle='rgba(0,0,0,.35)';c.beginPath();c.ellipse(0,box.r+7,box.r*1.4,7,0,0,TAU);c.fill();c.fillStyle='#f59e0b';c.fillRect(-18,-18,36,36);c.fillStyle='#d97706';c.fillRect(-18,-18,36,9);c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(-18,-18,36,36);c.beginPath();c.moveTo(-18,-18);c.lineTo(18,18);c.moveTo(18,-18);c.lineTo(-18,18);c.stroke();if(box.grab){c.strokeStyle='#a7f3d0';c.lineWidth=4;c.beginPath();c.arc(0,0,30,0,TAU);c.stroke()}c.restore();label('CRATE '+box.surface,box.x,box.y+44,'#fde68a')}
function player(showBody=1){let x=p.x,y=p.y-p.z*.25;if(showBody){c.fillStyle='#38bdf8';c.beginPath();c.arc(0+x,0+y,20,0,TAU);c.fill();c.strokeStyle='#fff';c.lineWidth=2;c.stroke();}c.save();c.translate(x,y);c.rotate(p.a);c.strokeStyle='#e0f2fe';c.lineWidth=5;c.beginPath();c.moveTo(0,0);c.lineTo(42,0);c.stroke();c.fillStyle='#fff';c.beginPath();c.moveTo(50,0);c.lineTo(34,-9);c.lineTo(34,9);c.closePath();c.fill();c.restore();if(showBody)label('PLAYER',x,y-26,'#bae6fd')}
function fxDraw(){for(const f of fx){let a=cl(f.life/1.8,0,1),col=f.k=='gravity'?'#c4b5fd':f.k=='crate'?'#fbbf24':'#93c5fd';drawArrow(f.x1,f.y1,f.x2,f.y2,col,a);label((f.k=='gravity'?'g/impulse ':'vel ')+Math.round(f.sp),f.x2,f.y2-10,'#fff')}}
function worldDraw(showBody=1){surfaceGrid();areaBoxes();if(A&&B){c.strokeStyle='rgba(147,197,253,.28)';c.setLineDash([9,6]);c.lineWidth=3;c.beginPath();c.moveTo(A.x,A.y);c.lineTo(B.x,B.y);c.stroke();c.setLineDash([])}portal(A,'#9fdcff');portal(B,'#c7b7ff');fxDraw();c.strokeStyle='rgba(167,243,208,.36)';c.lineWidth=3;c.strokeRect(goal.x-34,goal.y-34,68,68);label('GOAL',goal.x,goal.y-44,'#bbf7d0');crate();player(showBody);drawArrow(85,world.h-95,85,world.h-35,'#c4b5fd',.7);label('g 9.8 m/s²',120,world.h-60,'#ddd6fe')}
function screenWorld(showBody=1){let {sc,ox,oy}=roomTransform();c.save();c.translate(ox,oy);c.scale(sc,sc);worldDraw(showBody);c.restore()}
function drawMap(){screenWorld(1);hudText('MAP: áreas + superficies activas · '+activeSurface)}
function drawRoom(){screenWorld(1);c.fillStyle='rgba(0,0,0,.62)';c.fillRect(0,0,W,70*D);c.fillStyle='#fde68a';c.font=14*D+'px system-ui';c.textAlign='center';c.fillText('ALERTA: cuarto completo',W/2,23*D);c.fillStyle='#e0f2fe';c.fillText(cut.reason+' · regreso a '+cut.prev+' en '+Math.max(0,cut.t).toFixed(1)+'s',W/2,48*D)}
function drawGizmo(){screenWorld(0);hudText('GIZMO VIEW: estable, sin cuerpo · superficie '+activeSurface);c.fillStyle='rgba(15,23,42,.78)';c.fillRect(12*D,H-118*D,260*D,78*D);c.fillStyle='#dbeafe';c.font=12*D+'px system-ui';c.textAlign='left';c.fillText('Pos.Aya / WayPoint-O',24*D,H-92*D);c.fillText('rot x/y/z · surface '+activeSurface,24*D,H-70*D);c.fillText('g:'+world.g+'  mode:'+mode,24*D,H-49*D)}
function drawLoopH(){c.fillStyle='#101418';c.fillRect(0,0,W,H);let y=H*.54;c.strokeStyle='#64707b';c.lineWidth=18*D;c.beginPath();c.moveTo(40*D,y);c.lineTo(W-40*D,y);c.stroke();let sx=x=>40*D+x/world.w*(W-80*D);c.strokeStyle='#9fdcff';c.lineWidth=6*D;c.beginPath();c.ellipse(sx(A?.x||140),y,12*D,42*D,0,0,TAU);c.stroke();c.strokeStyle='#c7b7ff';c.beginPath();c.ellipse(sx(B?.x||840),y,12*D,42*D,0,0,TAU);c.stroke();c.fillStyle='#38bdf8';c.beginPath();c.arc(sx(p.x),y-p.z*.15,18*D,0,TAU);c.fill();drawArrow(sx(p.x),y,sx(p.x)+Math.cos(p.a)*60*D,y,'#e0f2fe',.9);c.fillStyle='#f59e0b';c.fillRect(sx(box.x)-17*D,y-17*D,34*D,34*D);for(const f of fx)drawArrow(sx(f.x1),y-55*D,sx(f.x2),y-55*D,f.k=='crate'?'#fbbf24':'#93c5fd',cl(f.life/1.8,0,1));hudText('LOOP H: entrada/salida lateral horizontal visible')}
function drawLoopV(){c.fillStyle='#101418';c.fillRect(0,0,W,H);let x=W*.52,top=110*D,bot=H-140*D;c.strokeStyle='#64707b';c.lineWidth=22*D;c.beginPath();c.moveTo(x,top);c.lineTo(x,bot);c.stroke();c.strokeStyle='#9fdcff';c.lineWidth=6*D;c.beginPath();c.ellipse(x,top,50*D,12*D,0,0,TAU);c.stroke();c.strokeStyle='#c7b7ff';c.beginPath();c.ellipse(x,bot,50*D,12*D,0,0,TAU);c.stroke();let py=bot-cl(p.z,0,210)/210*(bot-top);c.fillStyle='#38bdf8';c.beginPath();c.arc(x,py,18*D,0,TAU);c.fill();drawArrow(x+80*D,top,x+80*D,bot,'#c4b5fd',.8);drawArrow(x,py,x,py+p.vz*.12*D,'#fbbf24',.8);hudText('LOOP V: gravedad abajo · caída→impulso por portal')}
function drawFP(){let g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#111820');g.addColorStop(.5,'#343b41');g.addColorStop(1,'#15191e');c.fillStyle=g;c.fillRect(0,0,W,H);c.fillStyle='#737d84';c.fillRect(W*.58,H*.23,W*.35,H*.62);c.fillStyle='#4a535b';c.fillRect(0,H*.55,W,H*.18);if(A){c.strokeStyle='#9fdcff';c.lineWidth=7*D;c.beginPath();c.ellipse(W*.36,H*.50,24*D,78*D,0,0,TAU);c.stroke()}c.fillStyle='#f59e0b';c.fillRect(W*.62,H*.48,70*D,70*D);c.strokeStyle='#fff';c.lineWidth=3*D;c.strokeRect(W*.62,H*.48,70*D,70*D);drawArrow(W*.5,H*.75,W*.5+Math.cos(p.a)*90*D,H*.75+Math.sin(p.a)*25*D,'#e0f2fe',.8);if(tunnel>0){for(let i=0;i<24;i++){let a=i/24*TAU+performance.now()/150,r=W*.2+i*6*D;c.strokeStyle='rgba(191,219,254,'+(tunnel*.45)+')';c.beginPath();c.moveTo(W/2+Math.cos(a)*r,H/2+Math.sin(a)*r*.6);c.lineTo(W/2+Math.cos(a)*W,H/2+Math.sin(a)*H);c.stroke()}}hudText('FP: espada/marcador frontal entrando al portal')}
function hudText(t){c.fillStyle='rgba(0,0,0,.48)';c.fillRect(0,0,W,42*D);c.fillStyle='#e5e7eb';c.font=13*D+'px system-ui';c.textAlign='center';c.fillText('v1.9.0B2 · '+t,W/2,26*D)}
function draw(){c.fillStyle='#050607';c.fillRect(0,0,W,H);if(cut.on)drawRoom();else if(view=='map')drawMap();else if(view=='gizmo')drawGizmo();else if(view=='loopH')drawLoopH();else if(view=='loopV')drawLoopV();else drawFP();c.fillStyle='rgba(255,255,255,.78)';c.font=10*D+'px system-ui';c.textAlign='left';c.fillText('v1.9.0B2 · '+(cut.on?'cutaway':view)+' · grab '+(box.grab?'ON':'OFF')+' · surface '+activeSurface+' · '+(box.done?'SNAPPED':'movable'),12*D,H-14*D);if(box.done&&!cut.on){c.fillStyle='rgba(0,0,0,.46)';c.fillRect(0,H*.42,W,H*.15);c.fillStyle='#ecfdf5';c.font=22*D+'px system-ui';c.textAlign='center';c.fillText('STAGE 2 DESBLOQUEADO',W/2,H*.51)}}
function makePanel(){let g=document.createElement('div');g.id='gizmoPanel';g.style.cssText='position:fixed;left:8px;right:8px;top:calc(env(safe-area-inset-top) + 88px);z-index:12;display:none;gap:6px;flex-wrap:wrap';document.body.appendChild(g);let add=(t,f)=>{let b=document.createElement('button');b.textContent=t;b.style.minHeight='34px';b.onclick=f;g.appendChild(b)};add('Gizmo View',()=>{view='gizmo';say('Gizmo estable')});add('Surface',()=>{activeSurface=surfaces[(surfaces.indexOf(activeSurface)+1)%surfaces.length];say('Surface '+activeSurface)});add('Floor',()=>{activeSurface='floor'});add('Wall',()=>{activeSurface='wall'});add('Ceiling',()=>{activeSurface='ceiling'});add('Loop H',()=>setAreaPreset('loopH'));add('Loop V',()=>setAreaPreset('loopV'));add('Gravity Tube',()=>setAreaPreset('loopV'));add('Delivery',()=>setAreaPreset('delivery'));add('Sound ON',()=>{audioOn=1;say('Audio pendiente: no priorizado antes de core fun')});return g}
function cycle(){if(cut.on)return;view=view=='map'?'gizmo':view=='gizmo'?'loopH':view=='loopH'?'loopV':view=='loopV'?'fp':'map';say(view.toUpperCase())}
function init(){let panel=makePanel();$('helpBtn').onclick=()=>{panel.style.display=panel.style.display=='none'?'flex':'none'};$('debugBtn').onclick=()=>startCut('supervisión manual');document.querySelectorAll('[data-act]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();let a=b.dataset.act;if(a=='A'){A=makePortal('A',ptr.x,ptr.y,activeSurface);say('Portal A '+activeSurface)}if(a=='B'){B=makePortal('B',ptr.x,ptr.y,activeSurface);say('Portal B '+activeSurface)}if(a=='L')cycle();if(a=='T'){tunnel=1.2;say('Túnel temporal visual')}if(a=='F')toggleGrab();if(a=='X'){A=B=null;fx=[];trail=[];say('Clear')}});cv.onpointerdown=e=>{if(view=='fp'&&!cut.on){look={on:1,id:e.pointerId,x:e.clientX};cv.setPointerCapture&&cv.setPointerCapture(e.pointerId)}let r=cv.getBoundingClientRect(),sx=(e.clientX-r.left)*D,sy=(e.clientY-r.top)*D,{sc,ox,oy}=roomTransform();ptr={x:(sx-ox)/sc,y:(sy-oy)/sc}};cv.onpointermove=e=>{if(view=='fp'&&look.on&&e.pointerId==look.id&&!cut.on){p.a=norm(p.a+(e.clientX-look.x)*.006);look.x=e.clientX}else{let r=cv.getBoundingClientRect(),sx=(e.clientX-r.left)*D,sy=(e.clientY-r.top)*D,{sc,ox,oy}=roomTransform();ptr={x:(sx-ox)/sc,y:(sy-oy)/sc}}};cv.onpointerup=cv.onpointercancel=e=>{if(e.pointerId==look.id)look.on=0};let je=$('joy'),kn=$('knob');function jm(e){if(!joy.on||e.pointerId!=joy.id)return;let dx=e.clientX-joy.cx,dy=e.clientY-joy.cy,d=Math.hypot(dx,dy),m=38;if(d>m){dx=dx/d*m;dy=dy/d*m}joy.dx=Math.abs(dx/m)<.08?0:dx/m;joy.dy=Math.abs(dy/m)<.08?0:dy/m;kn.style.left=38+dx+'px';kn.style.top=38+dy+'px'}je.onpointerdown=e=>{let r=je.getBoundingClientRect();joy={on:1,id:e.pointerId,cx:r.left+r.width/2,cy:r.top+r.height/2,dx:0,dy:0};je.setPointerCapture&&je.setPointerCapture(e.pointerId);jm(e)};je.onpointermove=jm;je.onpointerup=je.onpointercancel=e=>{if(e.pointerId!=joy.id)return;joy.on=0;joy.dx=joy.dy=0;kn.style.left='38px';kn.style.top='38px'};onkeydown=e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=1;if(e.code=='KeyL')cycle();if(e.code=='KeyF')toggleGrab();};onkeyup=e=>{let m={KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',ArrowUp:'W',ArrowLeft:'A',ArrowDown:'S',ArrowRight:'D'};if(m[e.code])keys[m[e.code]]=0};setAreaPreset('loopH')}
function frame(n){let dt=Math.min(.05,(n-last)/1000);fps=fps?fps*.9+(1/dt)*.1:1/dt;last=n;update(dt);draw();if(msgT>0){msgT-=dt;if(msgT<=0)ui.m.style.display='none'}ui.st.textContent=box.done?'resuelto':(cut.on?'cutaway':'runtime-v1.9.0B2');ui.ec.textContent='surface portal + gizmo';ui.fps.textContent='fps '+Math.round(fps);requestAnimationFrame(frame)}init();say('v1.9.0B2: superficies + gizmo + loop portal');requestAnimationFrame(frame)})();